[package]
name = "gridzero-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "2.2", default-features = false, features = ["guest"] }
serde = { version = "1.0", features = ["derive"] }
